### PR TITLE
Image resolution and PDF page selection with libtexpdf backend

### PR DESCRIPTION
**Pull request by Omikhleia**
Three commits touching quite the same bits of code:
* This is the required C support for the possible enhancements evoked in #1346
  Outputters using the libtexpdf backend to compute an image size, such as "debug" and "libtexpdf", also return, as additional results on the `getImageSize()` method, the image resolutions in dots (pixels) per inch.
  This may be used by packages/classes to check images have an appropriate (e.g. print) quality regardless of their claimed size (in pt), or to downsize too resolved images, etc. - but that is a separate concern ; this PR just offers the tooling.
  Ex. with `documentation/gutenberg.png` (200 x 243 pixels) unscaled = 144pt x 174.96 pt at resolution 100 dpi x100 dpi.
  N.B. Libtexpdf's density is in pt/in. It's converted back to dpi, here, as it is more usual for users (who tend to know that decent print quality in the range of 300-600 for printed books, for instance)
* Add ability to select the page on a PDF image, i.e. `\img[src=somepdf, page=2]` (the default is obviously 1, with same behavior as before) = my misunderstanding of question #1515, but the idea is sound nevertheless.
* Additionally, image height and width parsed as `SILE.measurement` rather than complex frame dimensions (as discussed in #1267 and done on the raiselower package in #1506.

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Thanks for these contributions. Sorry it is taking me so long to review stuff these days. It's hard to get my own production work done, have a bunch of my own refactoring and development projects loaded up in my head, and reason well about contributions along other lines all at the same time.

**Comment by ctrlcctrlv** [comment]
I think that we should have a meta discussion about what's a _third-party package_ and what's supposed to be PR'd here, as @Omikhleia PR's a lot of stuff I consider packages.

Notably, SILE and (Xe|Lua|p)?(La)TeX(2e)? disagree on this issue:

https://github.com/ctrlcctrlv/sile-logos
image

Precedent says that in SILE this is firmly a third party package, while in (Xe|Lua|p)?(La)TeX(2e)? it's a core macro.

**Comment by alerque** [comment]
Yes, we do. We have several PRs here (including some of my own) that I plan to repurpose as packages. This PR however provides core tooling that would be needed by packages…

**Comment by ctrlcctrlv** [comment]
Oh, absolutely. I'm commenting on the all of @Omikhleia's PR's as a group—not this particular one, didn't even read the title, just your comment :joy:

**Pull request merged**
