### PR TITLE
Go back to testing latest lua

### PR DESCRIPTION
**Pull request by alerque**
Waiting on upstream luarocks release (should be this week) and action update to match

### CODE REVIEW

**Comment by Omikhleia** [comment]
@alerque The CI tests on 5.4.2 currently. Is this old PR still applicable?

**Comment by alerque** [comment]
Last I checked the CI env still had issues with 5.4.4, but it's been a while and notably GitHub Actions has a new Ubuntu image we're running in, so it may work now.

**Comment by alerque** [comment]
Looks like we're good. Lua 5.1 has been giving us trouble lately—the VM has been getting stuck regularly. I don't think this has anything to do with SILE and put a timeout on it lately so it doesn't eat through our CI quota. I guess I'll merge this and if we have any trouble we can re-evaluate.

**Comment by alerque** [comment]
Hm, also it looks like I cross wired a branch in here. Stand by.

**Pull request merged**
