### PR TITLE
Cleanup width calculations in leaders, especially dotfill

### LINKED ISSUE #859: Page numbers not aligned in table of contents in manual v0.10.2
The title says it all, I think. They used to be aligned in previous versions.

### PR DESCRIPTION
**Pull request by alerque**
Fixes #859.

Changes outcome of #243.

This includes both a fix for the line width problem and separately a different way of handling the spacing of dotfills. The previously discussion of dotfills attempted to keep one side of the dots (right) flush. This does slightly improve the looks of TOC where the page numbers happen to also be the same with (e.g. fonts with lining numbers) but it significantly negatively impacts edge cases such as when only 1 or 2 dots fit. Given the stretch/shrink scenario of spaces this had the potential to be very ugly.

This rehashes the solution to that. By not having any shrink and only stretch a lot of the worst cases look a lot better. At the cost of not lining up the end column any more the variation between odd/even (and the overall variance in general) is reduced.

If this new rendering is not agreeable it is possible to fix the buggy case and still use the fixed dot alignment, I just think it looks uglier.

### CODE REVIEW

**Comment by alerque** [comment]
Before:

image

After:

image

**Comment by alerque** [comment]
@dajare Any opinion on which leader alignment method is "better"?

**Comment by dajare** [comment]
For me, **definitely** the second. You can't have wavy dot-leaders! (in vertical alignment).

See [this, for example](https://archive.org/details/earlypoemsofwill00morr/page/n13/mode/2up) more or less at random. Your "after" is in that family. (imo, ymmv, etc.) & FWIW!

**Comment by alerque** [comment]
For reference here is what the manual's TOC will look like with this fix and change:

image

There are still some "bad" visual artifacts here, but they are the result of the different font sizes and the font's side-bearing increasing with size. That issue of visual alignment is a can of worms not related to the dotfill at all!

**Comment by alerque** [comment]
@dajare Actually _both_ before and after situations here will result in wavy leaders. The situation is just sligtly less pronounced. The example you linked to is interesting in that it's a horizontal grid. No amount of fiddling with the current leader function will get anywhere close to that result, but it's an interesting option. If that's something desirable we should write a new package for `gridleaders` or something like that. Can you open an issue for that as a feature request? The way that will need to be implemented is just entirely different than what we have now, but the math for a horizontal grid might be very useful in other situations as well and probably a tool we should be providing.

**Comment by alerque** [comment]
Also, *mad respect* for craftsmen that did typesetting like that my hand!

**Comment by dajare** [comment]
> If that's something desirable we should write a new package for `gridleaders` or something like that. Can you open an issue for that as a feature request?

Can do. I'll try to supply some documentation, and get to this soon (before I forget!). (Btw - I thought a series [on this blog](https://dave.autonoma.ca/blog/) might interest you for obvious reasons!)

**Comment by dajare** [comment]
@alerque P.s., also FWIW, Bringhurst [eschews dot leaders in ToCs](https://twitter.com/teropa/status/1028669612618141696), claiming they "force the eye to walk the width of the page like a prisoner being escorted back to its cell." Not sure I agree (the audacity!) — rather, they guide you gently to your destination, ensuring you don't get lost on the way!

**Comment by dajare** [comment]
> ...Can you open an issue for that as a feature request?...

Done! Issue #875

**Pull request merged**
