### PR TITLE
Fix polish compound hyphen rule

### LINKED ISSUE #1960: Hyphenation on words joined with hyphen in Polish
Rumour has it that in Polish, when a word containing a hyphen is cut at that point, the hyphen must be repeated on the next line -- and that several typesetting systems have unaddressed enhancement requests on that topic:

Typst (issue in 2024): https://github.com/typst/typst/issues/3235
OpenOffice (issue in 2006): https://bz.apache.org/ooo/show_bug.cgi?id=71679

If this typography convention for Polish is correct, then SILE too is currently wrong:

```
\begin[papersize=a5]{document}
\language[main=pl]
\lua{
    for i = 1,100 do
       SILE.typesetter:typeset("biało-czerwony ")
    end
}
\end{document}
```

image

Except that it would be a _fairly trivial thing_ to fix... Just a few lines of code, possibly:
(EDIT: Well, a bit more, see PR)

```
-- Put this in languages/pl.lua
SILE.nodeMakers.pl = pl.class(SILE.nodeMakers.unicode)

function SILE.nodeMakers.pl:handleWordBreak (item)
  if item.text == "-" then
    self:addToken(item.text, item)
    self:makeToken()
    coroutine.yield(SILE.nodefactory.discretionary({
      postbreak = SILE.shaper:createNnodes("-", self.options)
    }))
  else
    self._base.handleWordBreak(self, item)
  end
end
```

image

Yay! :smile: 

---

I could make a PR, but the details are in the devil. Here I stack the "-" onto the previous word, and insert a postbreak discretionary. 
But we could also stack the "-" on the next word, or even wholly ignore it (of course, each time using an adequate postbreak/prebreak/replacement discretionary). 

The question at stakes is how is supposed to be hyphenated the first word?

With the above fix, we get bia•ło-•czer•wony (I am marking the hyphenation points with • to distinguish them from the word's hyphen)
... because `SILE.typesetter:typeset(SILE.showHyphenationPoints("biało-, "pl"))` :arrow_right:  bia•ło-

But note that `SILE.showHyphenationPoints("biało", "pl")` :arrow_right:  biało (EDIT: no hyphenation point currently)
... so depending on how we do it, we can get different hyphenations...

It _seems_ to me that bia•ło-•czer•wony might be correct, but we'd need a Polish friend to confirm the expectations :poland: 

EDIT I corrected `SILE.showHyphenationPoints("czerwony", "pl")` :arrow_right:  czer•wony (not czer•wo•ny) with default settings.

### PR DESCRIPTION
**Pull request by Omikhleia**
Closes #1960 

The sheer superiority of SILE over other typesetting systems (add lots of smiley faces).

### CODE REVIEW

**Comment by Omikhleia** [comment]
Lol.

image

Good on first occurrence (lines 2-3), but bad of on subsequent one (lines 4-5). Back to the working bench.

**Comment by Omikhleia** [comment]
> Good on first occurrence (lines 2-3), but bad of on subsequent one (lines 4-5). Back to the working bench.

Got it. I never understood fully the ICU stuff (and when debugging, it seems to show some weird re-entrance). Anyhow, ICU will also mark word boundaries as (line) breaks, and we get a penalty (0) in those case. Here just after a "special" discretionary, we need to cancel it....

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
FreeBSD test is failing because 12.x is EOL now. I fixed that and added tests for 14.x to the `develop` branch work along with appropriate dependency updates. I may get a minute to backport that, but even if not I think we could safely ignore the FreeBSD testing for this and any other of the v0.14.x releases.

**Comment by alerque** [comment]
Hopefully [my rehash of the test case](https://github.com/sile-typesetter/sile/compare/222ec2ca3578711da3d0fbc87955d130345f0d2d..af9cabf88c78ba0ceb21e74bfe11d147b582d022) captured the ethos of what was being tested here with 120 less lines of debug data and long lines of prose to parse when reviewing test changes later.

**Review by alerque — APPROVED** [review]

**Pull request merged**
