### PR TITLE
Correct font-variants using opsz axis

### PR DESCRIPTION
**Pull request by alerque**
Follow up to #1662 with patch mentioned in #1265.

### CODE REVIEW

**Review by ctrlcctrlv — APPROVED** [review]

**Comment by simoncozens** [comment]
OK, so I've been pretty absent all year and I probably don't have much right to speak into this, but this seems like a strange special case: one specific axis instead of arbitrary axes. I know we're not currently able to do *much* with variable fonts until we work out instantiation and putting them into a PDF, so we're just making GSUB variations work, but I would feel more comfortable with a plan to pass arbitrary designspace locations from the user into the shaper rather than hacking one axis in to make one of Fred's fonts work...

**Comment by alerque** [comment]
I think that desire is reasonable but also covered by other issues. Passing all axis data is definitely on the list but also basically equivalent of variable font support. In the mean time I don't at all mind dabbling in support like this even without the whole enchilada.

**Comment by ctrlcctrlv** [comment]
@simoncozens `opsz` will always need to be special cased, as you cannot get it directly from the input given to the other axes, it comes from the font's size; most (free) applications, if they support `opsz`, don't even let you set the axis independently of the font's size.

**Comment by ctrlcctrlv** [comment]
(So what I'm trying to say is even though I benefit the most from this patch, this is a sane way to do it, and when we add generic varfont axis setting then users can change the `opsz` independently of the font's size if they so choose.)

**Comment by khaledhosny** [comment]
I’m working on #1182 and will send a PR later today, and I used a slightly different approach to this.

**Pull request merged**
