### PR TITLE
%fw ⇒ %fh

### PR DESCRIPTION
**Pull request by meisterluk**
frame height is denoted as `%fh`

### CODE REVIEW

**Comment by alerque** [comment]
Can you change the commit message to `docs(measurments): Correct frame height relative unit to %fh` or similar so we can merge? You can use `git commit --amend` then `git push --force` to get the change here.

**Comment by alerque** [comment]
If not I'll do so the next time I'm at a computer.

**Comment by meisterluk** [comment]
No problem, done!

**Comment by alerque** [comment]
@meisterluk Congratulations on doing exactly as I said, complete with a spelling mistake (measurments→measurements) which the commitlint bot won't let slip. I just fixed it for you, sorry for the trouble ... but the structured commit history really does make change log management and cutting new releases a lot easier.

**Pull request merged**
