### PR TITLE
Cleanup after repository migration to org namespage

### PR DESCRIPTION
**Pull request by alerque**
- [x] Update links to repository
- [x] Make sure Travis CI works again
- [x] Make sure Lua coveralls reports work again
- [ ] Make sure Azure CI works again
- [x] Make sure PR workflow with required checks are connected to the right checks again
- [ ] See about moving the Gitter chat namespace to match

### CODE REVIEW

**Comment by alerque** [comment]
I just authorized Travis to access the new Github Organization.

**Comment by alerque** [comment]
By the way @simoncozens your membership in this Github Org is listed as "private". This has the effect of the public "people" listing not showing you as part of the effort to anyone but yourself and me. That seems less than ideal — unless you're hiding ;-)

**Comment by rjmunro** [comment]
Another piece of cleanup at some point it might be good to remove the gh-pages branch and make sile-typesetter.org into  ["organisation pages"](https://help.github.com/en/articles/user-organization-and-project-pages). That means the website will be it's own project, with it's own issues, branches and pull requests.

(You might think having it in the same repo as the project might be good because when you push a new release of the project it can push a new release of the website, but due to gh-pages being a branch it doesn't work like that)

**Comment by alerque** [comment]
Thanks for the tip @rjmunro, and I agree that's probably the best way to proceed. We _can_ actually connect releases to automatic updates of the other branch via hooks and CI builds (in fact I was already moving that way, see #588) but the tooling is complicated ... and we can still to it in a separate repo too. A release in one repo can actually trigger actions in another.

**Comment by alerque** [comment]
I haven's looked into Azure yet, but I'm guessing you might have to fix that @simoncozens. Unless they have magic like Travis that matches logins to Azure with Github user & org permissions. I'm out of here for now and will look at it later, but that an Gitter might be left for you.

**Comment by rjmunro** [comment]
Yes, I meant that having the site in the same repo as a gh-pages branch didn't make things any easier than having it in a separate repo.

One more thing I've noticed: The site-typesetter organisation doesn't have a logo / icon / avatar thing.

**Comment by alerque** [comment]
I opened #674 as a separate issue because it shouldn't be holding up this and other PRs, and the Gitter issue is super low priority.

**Pull request merged**
