### PR TITLE
Properly justify lines containing ligatures (workaround)

### PR DESCRIPTION
**Pull request by Omikhleia**
Partial workaround for #1362, with two concerns in mind:
- Re-shuffle things in computeLineRatio to at least meet the expectation of nnode output so that lines wish ligatures, with fonts where those can be shorter than the non-ligatured text, are correctly justified.
- Store the natural width of the line, so that other packages that may need it (e.g. see #1344) don't need to recompute it and meet the same issues again.

Before:

image

After:

image

It's kind of beating the wind (it does not address the core issue and as the second part of the test shows, doesn't fix therefore ligatures in hyphenated words...), but at least it provides correct justification.

### CODE REVIEW

**Comment by Omikhleia** [comment]
Two existing tests are impacted:
- tests/bug-283.sil
- tests/bug-79.sil
Unless I have dust in my eyes (which is possible!), the effect on them is hardly noticeable and seem correct to me. My feeling is that some font kerning (similar but much smaller effect than the ligatures that triggered this ticket) is at play. I leave you judge...

**Comment by ctrlcctrlv** [comment]
Do you mind retitling the PR to "Justify lines with ligatures more narrow than unligated" or something? If I was confused…

**Comment by ctrlcctrlv** [comment]
Also I know there's a limit on commit name length, but not on PR title length, so no need to change your commit title

**Comment by alerque** [comment]
> "Justify lines with ligatures more narrow than unligated"

That would be a good *issue* title, but this isn't the issue report it is a proposed action to fix it.

**Comment by ctrlcctrlv** [comment]
@alerque Sure, it just made me think all my documents were broken until I carefully read the issue :-)

**Comment by alerque** [comment]
> Sure, it just made me think all my documents were broken until I carefully read the issue :-)

Most of mine *are* :frowning:. The level of brokenness is relatively minor in my case because Turkish rarely runs into ligatures, but it I reviewed a bunch of old publications and clearly the kerning has been affecting my justification just a little bit on a regular basis.

**Comment by Omikhleia** [comment]
@alerque If I am not mistaken (based on the front matter), you typeset a book named "Plan". It could be interesting to check if the suggested workaround at least improves what seems to be similar justification issues there, or if they are other causes?
test-plan-justify

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
Definitely a bit of a hack I'd like to see refactored, but it isn't immediately apparent to me what a better interface would look like without other major refactorings first. In the mean time it is hard to deny the current output is bogus and this is clearly correct in more cases.

After squinting at the two affected tests I agree the output is more correct. In some cases the overflow is *bigger*, but that appears to be because the bug causing hyphenation overflows is not being partially compensated for visually by otherwise bogus under-calculations.

**Pull request merged**
