### PR TITLE
Stricter color parsing and improved color package documentation

### LINKED ISSUE #1440: SILE.colorparser is not strict enough
SILE 0.12-0.13.0

An easy issue ;-)

```
> a = SILE.colorparser("abcd#123456efgh"); print(SU.dump(a))
{
  b = 0.33725490196078,
  g = 0.20392156862745,
  r = 0.070588235294118
}
```

- IMHO, it should reject invalid color specifications (hint: the current regexps should be `^whatever$`)
- ~~(By the way, we could also support `rgb(r, g, b)` (à la CSS) besides the current `r g b` -- it wouldn't cost much.)~~ Let's not add more code clutter here. Percentages might be interesting (as colors are sometimes defined in %s rather in 0..255 scale), but other "weird" CSS-like sugar-syntaxes are not that interesting. 
- EDIT: improving the "color" package doc would be a plus... (mentioning CMYK, etc.)

### PR DESCRIPTION
**Pull request by Omikhleia**
Closes #1440 

This proposed PR does the the following things:
- `SILE.colorparser` is made more robust
- A "busted" test is added
- **color** packgage documentation is improved (see note below)
- Additionally:
  - Colors in RGB or CMYK can also be expressed in percentages besides values in the 0..255 range. Just a small convenience, but why not, as (esp. CMYK) colors are sometimes defined in %s.
  - Named colors are made case-insensitive (as in CSS, so that one can use e.g. "AntiqueWhite" besides "antiquewhite")

Note: All color specifications are now described in the package documentation. Mentioning CMYK might open a Pandora box, as I have no idea what our ICC profile is. The not-so-obvious relationship between (device-independent) RGB and CMYK might therefore surface at some point -- And people might be surprised that "naive" CMYK-RGB conversions (I am here using the same "naive" term as used in the CSS specs) won't always lead to the same colors... But anyhow my take on this is simple: document what we do, period. Question may arise, and be addressed later.

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by Omikhleia** [comment]
So `SILE.coloparser` goes away for `SILE.color` in that unrelated branch?

Beware, I am getting annoyed...

**Comment by alerque** [comment]
If you'd rather I refactor in a follow up commit(s) instead of the same PR that's fine I can do that. But whether in related PRs or separately I'm really pushing to fix the overall code layout so that SILE can be used programmatically as a library. I've been frustrated by years by not being able to move on with that, and lately I've found any attempt to swap out bits with much faster Rust alternative is also kind of dependent on the same refactoring. Any time I have to review code is a good time to fix scope issues in those bits.

**Comment by Omikhleia** [comment]
> ...  faster Rust alternative ...

I am even more annoyed.

As a package/class designer and book writer, I've lots of "surface" changes to keep up-to-date, without any immediate added functional value. I have 20+ packages, that I need to update, without any visible added-value. Bugs are still there. Missing features are still there. No one is even working seriously on the SILE 1.0 target - i.e. at least trying something... (no one, [really](https://github.com/Omikhleia/omikhleia-sile-packages/pull/22).

But `SILE.colorparser`, sure, has to become `SILE.color` - That's SO important.

You lost me, here, I'm afraid...

**Comment by Omikhleia** [comment]
I could add, but that would be desperate: My next book will be in Markdown and will likely use Pandoc + OpenOffice. I do think I have failed somewhere, but the book must exist, regardless of the solution to typeset it :(

**Comment by alerque** [comment]
I'm sorry I'm not doing a great job of communicating the *why* behind some recent changes. I've been frustrated for years with 20+ minute turnaround times to tweak something and render a book to the page with an issue. 95% of the time in SILE is spent in a few some small loops that could be 1000× faster, but to handle them faster while still giving users the flexibility to change anything they want in Lua we have to have consistent data types.

The change from `colorparser()` to `color{}` was not a willy-nilly name change. I changed a function returning a table with different properties depending on the input to a class with consistent properties and methods for all inputs. This is is now a data type that we'll be able to codify and pass around between languages and implementations.

I also shimmed it from the old version so you don't have to do *anything* to your documents or code yet—at least for several major versions because the old interface will keep working.

**Comment by alerque** [comment]
> No one is even working seriously on the SILE 1.0 target - i.e. at least trying something... (no one, [really](https://github.com/Omikhleia/omikhleia-sile-packages/pull/22) ?).

My work on refactoring inputters was directly related to setting up for USFX / OSIS input processing.

**Comment by RobH123** [comment]
> > No one is even working seriously on the SILE 1.0 target - i.e. at least trying something... (no one, [really](https://github.com/Omikhleia/omikhleia-sile-packages/pull/22) ?).
> 
> My work on refactoring inputters was directly related to setting up for USFX / OSIS input processing.

[Again](https://github.com/sile-typesetter/sile/issues/1398#issuecomment-1133766650), hopefully you mean USX (widely-used Bible format), not USFX (only eBible.org).

**Comment by Omikhleia** [comment]
> 95% of the time in SILE is spent in a few some small loops that could be 1000× faster

I don't care the time, if the output is neat. I run SILE, drink a coffee or tea, and enjoy the PDF. Doesn't take _that_ long . Then proofreading starts, and the time SILE took processing the initial input doesn't even compare...

**Comment by Omikhleia** [comment]
@RobH123 
> [Again](https://github.com/sile-typesetter/sile/issues/1398#issuecomment-1133766650), hopefully you mean USX (widely-used Bible format), not USFX (only eBible.org).

Again, as I _already_ said there: provide me a bible in French and USX, and I will try _likewise_. But I only found Segond in USFX... So good is the "widely-used" USX, it doesn't care about French apparently... And anyhow, it doesn't _really_ matter, once one has the tooling, the format is secondary. You are perhaps biased and missing the whole point? (There might be some chapel issue between eBible and the other one? How can I know... Oh my, I'd die for a Bible, in any stupid XML format, to be typeset with SILE. That would be so cool, be it USFX, USX or whatever... And... Oh my. I am not _even_ a Christian. Oops. Now you know. Sorry about that...)

**Comment by Omikhleia** [comment]
> > 95% of the time in SILE is spent in a few some small loops that could be 1000× faster
> 
> I don't care the time, if the output is neat. I run SILE, drink a coffee or tea, and enjoy the PDF. Doesn't take _that_ long . Then proofreading starts, and the time SILE took processing the initial input doesn't even compare...

SILE: a few minutes.
Proofreading... You only see half of the post-its, and it was already in the 3rd "final" proofreading session, with two reviewers in addition to me.
image

What _time_ are we discussing here?

**Comment by alerque** [comment]
I'm not asking you to care about the speed, and as far as I know I haven't broken any of your code. I've worked hard (up to weeks of work the the case of the document class changes I made in 0.13.0) making sure shims are in place to keep old documents compiling as much as possible. If you're worried about the deprecation notice 2 major versions out, `sed -i -e "s/SILE.colorparser/SILE.color/g" *` should do the trick.

None of this will slow down your proofreading time. On the other hand I have watched over 1,500 hours (hours, not minutes, over half a year of work time) go by waiting for SILE builds and fresh PDFs—and many more man hours than that have slipped by as larger teams waited on output. Sure we try to fill the time, but the turn around cycle from edits to new output is too long for some workflows right now! I'm not asking you to care, but I do not believe that cleaning up the SILE internals so that it *could* be addressed is going to be bad for anybody in the long run.

**Pull request merged**
