### PR TITLE
fix(languages): Stop Japanese resetting global chapter post macro

### LINKED ISSUE #990: tate and the immortal 章
Importing `tate` creates a 章 that persists despite a call to `\language`, and despite the fact that `tate` allegedly no longer calls `\language` itself.

SILE v0.10.9.r36-gf16af44, Xubuntu 20.04

```tex
\begin[class=book]{document}
\script[src=packages/font-fallback]
\script[src=packages/tate]
\define[command=open-double-page]{\noindent\par}
\language[main=en] % I don't seem to matter :-(
\font:add-fallback[family=Noto Serif CJK JP]
\chapter{It's all good in the hood}
It is
\section{Wait, maybe it's not...}
Oh no
\language[main=ja]
\chapter{私たちの近所で、すべてはいつも大丈夫だぜ！}
うん、そう
\section{いつもいつも}
いつもだぜ
\end{document}
```
image

Workaround: 
```tex
\define[command=book:chapter:post]{\skip}
```

### PR DESCRIPTION
**Pull request by alerque**
Fixes #990

### CODE REVIEW

**Comment by simoncozens** [comment]
That's weird. Did I not PR it?

**Comment by alerque** [comment]
Nope, I found the commit in a branch but there was no PR.

I took your test and expanded it to cover the other languages that currently could have messed this up (but were okay), and also simplified the output just a little.

**Comment by simoncozens** [comment]
Thanks!

**Comment by alerque** [comment]
If would have helped if I updated the expected test output at the same time as I changed the input. Oops.

**Pull request merged**
