### PR TITLE
Fix(languages): Correct punctuation rules for French

### PR DESCRIPTION
**Pull request by Omikhleia**
This PR is my take at #704, starting anew and fresh. 

I used it it on my "test" article and found it neat, with no hanging punctuation at the beginning of lines, and good spaces where they should be. Just an extract :

image

I also tested the "exception" cases:

image
'
I noticed that with some fonts, the shaper could have pre-processed some ligatures (such as !?) as one "item", so I took that too into account.

Any other Frenchman than I, for a double-check ? ;)

### CODE REVIEW

**Comment by Omikhleia** [comment]
Hmm, there's something wrong later in my "test" article - a missing hyphenation dash.

image

Not sure how it could be related, though.

**Comment by Omikhleia** [comment]
> Hmm, there's something wrong later in my "test" article - a missing hyphenation dash.

An another one
 
image

The root cause seems to be here:

image

If I remove the penalty, the issue disappears - but it somehow means not using much of that ICU logic... Actually I don't understand that ICU logic here, since we have hyphenation patterns and the Knuth line-breaking algorithm. Could it be that ICU inserts inappropriate breakpoints, or puts the line-breaking algorithm at pain?

**Comment by Omikhleia** [comment]
Worked around the abovementioned issue, added a test case for #704, fixed the two other tests for #621 and #702 after I had checked their correct result with the new punctuation definitions. AFAIC, I am done on this topic for now - moving to the next one !

**Comment by simoncozens** [comment]
Wonderful - thank you!

**Comment by alerque** [comment]
For future reference the conventional-commit scope tags on these commits will make them show up a bit strange in the next release: 95c2398 is good, ed8734c should have been `chore(languages)` or maybe `feat(languages)`, and 8e9b056 should have been `test(languages)`.

Thanks for the expertise and time to contribute this @Omikhleia ! (← thin space)

**Comment by simoncozens** [comment]
I’ve been thinking about this. The original purpose of conventional commit messages for us was to help generate release notes. I’m eager not to turn a maintainer aid into a contributor burden. For the purpose of generating release notes (which deal with changes less granular than individual commits, and more often at the PR level of granularity), we don’t actually need to enforce them on every single commit. And now that master is protected, we get to rewrite the commit message into a PR-level summary when we squash and merge. So why don’t we just require conventional commits, only by maintainers, at squash time?

**Comment by alerque** [comment]
Because we don't require granular enough PR's that we can squash them. In fact they very frequently touch several different things, hence the commit level is usually where the release notes come from, not the PR level. We could have a PR/squash level workflow but we would need to enforce a lot more granular PRs. Personally I think that's more of a contributor burden than commit messages. I can and frequently do fixup commit messages in PRs so I'm not that concerned with contributors getting it right (see e.g. the math PR history vs the original branches!), you just merged this one before I got to it. Whether it is checking the messages in a PR or writing PR squash messages you and I as maintainers are still responsible for this.

**Pull request merged**
