### PR TITLE
Fix debug frame ids

### LINKED ISSUE #915: \language[main=ja] breaks \showframe
(This is a contrived example. By the time I discovered the problem, I realized frames are not a good solution to my problem. But, this is still a bug.)

```tex
\begin[class=book]{document}
\script[src=packages/frametricks]
\language[main=ja] % uncomment me to break everything
\begin[first-content-frame=tate1]{pagetemplate}
\frame[id=tate1,
left=left(content),right=right(content),bottom=top(content),next=content,height=40pt]
\end{pagetemplate}
\font[family=Noto Serif CJK JP]
\showframe
よくある質問（英語：FAQ）

よくある質問（英語：FAQ）

よくある質問（英語：FAQ）

楽しい答え（英語：FAQ）

楽しい答え（英語：FAQ）

楽しい答え（英語：FAQ）
\showframe
\end{document}
```

```
This is SILE v0.10.5
<showframe.tex>

Error detected:
	/usr/share/sile/core/libtexpdf-output.lua:151: attempt to index field 'nodes' (a nil value)
stack traceback:
	/usr/share/sile/core/libtexpdf-output.lua:151: in function 'debugFrame'
	/usr/share/sile/packages/frametricks.lua:149: in function '?'
	/usr/share/sile/core/sile.lua:284: in function 'call'
	/usr/share/sile/core/inputs-common.lua:65: in function 'process'
	/usr/share/sile/core/inputs-texlike.lua:164: in function 'process'
	/usr/share/sile/core/sile.lua:237: in function 'readFile'
	/usr/bin/sile:62: in function </usr/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/bin/sile:62: in main chunk
	[C]: in ?
```

### PR DESCRIPTION
**Pull request by simoncozens**
My version of #920.

Closes #915.

### CODE REVIEW

**Comment by simoncozens** [comment]
Of course it strikes me that the original failure will still happen in the unhappy case that the frame ID contains no Latin characters.

**Comment by alerque** [comment]
I was just going to say, how is Gentium going to handle the test case — for which it doesn't have glyphs. Maybe we shouldn't be mucking around with the glyph ids there at all. Otherwise this is more to the point than my PR.

**Comment by simoncozens** [comment]
This handles the test case just fine - in test case, the frame ID was "content" all along. That was being mangled when we tried to shape it using Noto CJK JP. It displays fine in Gentium.

It turns out that having non-ASCII frame IDs causes cassowary to have conniptions, so maybe my concern isn't a big deal.

**Comment by alerque** [comment]
> It turns out that having non-ASCII frame IDs causes cassowary to have conniptions

Really? I definitely saw some non-ASCII frame IDs in debugging and they didn't seem to be an issue. If fact the test case for this issue has one:

image


Is this a function of Cassowary not doing any real work on it? We should probably fix wherever the non-ASCII hang up is...

**Comment by simoncozens** [comment]
Those *are* ASCII frame-IDs. They're being mangled by the shaping, which is what this PR fixes.

**Comment by alerque** [comment]
Gah. I missed the fact that you (probably accidentally) *downgraded* the libtexpdf module as part of this PR. Maybe a little too aggressive with the `git add` foo?

**Comment by simoncozens** [comment]
Oops, sorry about that. Serves me right for using the GUI not the command line.

**Pull request merged**
