### PR TITLE
chore(tooling): Bounce non-GNU make at the door

### PR DESCRIPTION
**Pull request by alerque**
@simoncozens Does this error out with a useful message in BSD make or does it have syntax problems before it processes this far?

### CODE REVIEW

**Comment by simoncozens** [comment]
Neither - doesn't seem to do anything.

**Comment by alerque** [comment]
Hm, I wonder if the test itself is a Gnuism, try this as `make` and `make debug`:

```makefile
.PHONY: default debug

STATUS = $(shell echo gnuish)

default $(MAKECMDGOALS): debug

debug:
	@echo Test ran, explicit goals: $(MAKECMDGOALS)
	@echo Status var set as: $(STATUS)
```

As I understand it non GNU Make should have an empty STATUS variable here, but maybe the MAKECMDGOALS isn't triggering the test. I get:

image

I would expect BSD make to be the same except to never output anything but an empty STATUS, not `gnuish`.

**Comment by simoncozens** [comment]
With BSD make:

```
simon@upo ~ $ make
Test ran, explicit goals:
Status var set as: gnuish
simon@upo ~ $ make debug
make: Circular debug <- debug dependency dropped.
Test ran, explicit goals: debug
Status var set as: gnuish
```

**Comment by alerque** [comment]
So you're saying [this SO answer](https://stackoverflow.com/a/16550052/313192) is no longer valid?

**Comment by alerque** [comment]
>  I added the line `echo "You have GNU make"` to the `gnumake` target

That doesn't sound like you tested the right thing. Try this:

```makefile
MYVAR=$(shell echo foo)

default:
	@echo RESULT: $(MYVAR)
```

If BSD's make tells you `RESULT: foo` then I guess they've fixed that issue and brought it closer to feature parity with GNU-Make, making it harder to detect

**Comment by alerque** [comment]
image

**Comment by simoncozens** [comment]
Oh for goodness sake. Mac OS X make is now (as of I don't know when) gnu make.

**Comment by alerque** [comment]
@simoncozens Now I've forgotten what the original thing was you tried to do that `make` on your system failed for. There was something `gmake` worked when `make` didn't. Can you remind me what that was and shoot me any relevant version differences so I can debug the original problem?

**Comment by simoncozens** [comment]
Turns out to be nothing to do with GNU make, but this is what it was:

```
$ gnumake lua_modules
Makefile:1124: *** unterminated call to function `foreach': missing `)'.  Stop.
```

Still seeing it today. Here's the generated makefile:

```Make
lua_modules: $(LUAMODSPEC) $(shell $(rocksmatch) || echo force)
    if test -e .git; then
        $(LUAROCKS) $(LUAROCKSARGS) install --only-deps $<
    else
        rm -rf lua_modules
        cp -a lua_modules_dist lua_modules
        $(foreach LUA,$(filter-out $(LUA_VERSION),$(SUPPORTED_LUAS)),
        find lua_modules -maxdepth 3 -type d -name "*$(LUA)" -execdir rm -rf {} \;)
    fi
```

**Comment by alerque** [comment]
That `$(foreach ...)` is _not_ un-terminated according to my GNU Make. I wonder if autoconf is actually doing some monkey business, detecting something on the platform, and trying to downgrade syntax even though you don't need it too. That or you have a really old GNU Make or something like that.

I'll try another approach to that specific problem, but its also a pattern I used quite a lot in CaSILE. For example is it just having trouble with the newline or something else. Can you try this with semi-colon instead of line break command separators:

```diff
--- a/Makefile.am
+++ b/Makefile.am
@@ -90,8 +90,7 @@ lua_modules: $(LUAMODSPEC) $(shell $(rocksmatch) || echo force)
    else
        rm -rf lua_modules
        cp -a lua_modules_dist lua_modules
-       $(foreach LUA,$(filter-out $(LUA_VERSION),$(SUPPORTED_LUAS)),
-       find lua_modules -maxdepth 3 -type d -name "*$(LUA)" -execdir rm -rf {} \;)
+       $(foreach LUA,$(filter-out $(LUA_VERSION),$(SUPPORTED_LUAS)),find lua_modules -maxdepth 3 -type d -name "*$(LUA)" -execdir rm -rf {} \; ;)
    fi
 
 $(LUAMODLOCK): lua_modules $(LUAMODSPEC)
```

**Comment by alerque** [comment]
Oh bah. I'm testing from git, this _has to be_ tested from the dist bundle.

**Comment by simoncozens** [comment]
The one gives me:

```
if false; then
bash: -c: line 1: syntax error: unexpected end of file
```

**Pull request closed without merging**
